#!/usr/bin/env python
"""Usage: my_program [options]

Options:
--all             List everything.
--long            Long output.
--human-readable  Display in human-readable format.
"""
from docopt import docopt


if __name__ == '__main__':
    arguments = docopt(__doc__, version='Naval Fate 2.0')
    print(arguments)
